export { menu };
const menu = [
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    type: `Milk Tea`,
  },
  {
    name: `Oolong Milk Tea`,
    boba: true,
    price: 6.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    type: `Milk Tea`
  },
  {
    name: `Matcha N' Jasmine`,
    boba: true,
    price: 7.5,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    type: `Milk Tea`
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
  {
    name: `Trio Milk Tea`,
    boba: true,
    price: 7.0,
    image:"https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_115,q_auto:low,fl_lossy,dpr_2.0,c_fill,f_auto,h_123/fr78rt0x2xnxzkgyw23d",
    inStock: true,
    milkBased: true,
  },
];
